name: Deploy Vite React App

on:
  push:
    branches:
      
main
pull_request:
  branches:
main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      
name: Checkout code
      uses: actions/checkout@v3

      # Setup Node.js environment
      
name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify the Node version as per your requirements

      # Install dependencies
      
name: Install dependencies
      run: npm install

      # Build the Vite app for production
      
name: Build Vite React app
      run: npm run build

      # Deploy the built files to GitHub Pages
      
name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Vite's default build output directory